theme: jekyll-theme-minimal
title: Ethan Lampone Project Homepage
description: This is my very first GitHub Pages. Here I will showcase any future projects I will be working on and past ones I have done too. Stay tunned!
