theme: jekyll-theme-minimal
title: Ethan Lampone Project Portfolio
description: Data Science, Data Analysis, Machine Learning, and A.I Projects

## Personal Info
name: Ethan Lampone
email: lamponee721@outlook.com
github_username: EthanLampone
LinkedIn: https://www.linkedin.com/in/elampone/
